# Generated by Django 5.0.6 on 2024-06-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0002_alter_dish_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_name',
            field=models.CharField(max_length=180, unique=True),
        ),
    ]
