# Generated by Django 5.0.6 on 2024-06-21 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0003_alter_dish_dish_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='user',
        ),
    ]
